# -*- coding: utf-8 -*-
"""app_heathcare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXlD8VzKj97ufbv9-gio7QKcKCcNiAkH
"""


import streamlit as st
import os
import pickle
from chatbot import get_healthcare_response

st.set_page_config(page_title="Healthcare Chatbot", page_icon="💬")
st.title("💬 Healthcare Assistant Chatbot")
st.markdown("Ask health-related questions (e.g., symptoms, wellness, nutrition).")

HISTORY_FILE = "Healthcare_chatbot.pkl"

# Load saved chat history if exists
def load_history():
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, "rb") as f:
            return pickle.load(f)
    return []

# Save chat history to file
def save_history(history):
    with open(HISTORY_FILE, "wb") as f:
        pickle.dump(history, f)

# Initialize session
if "messages" not in st.session_state:
    st.session_state["messages"] = load_history()

# Display messages
for msg in st.session_state["messages"]:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Input
user_input = st.chat_input("Ask your healthcare question here...")

if user_input:
    st.session_state["messages"].append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    response = get_healthcare_response(user_input)

    st.session_state["messages"].append({"role": "assistant", "content": response})
    with st.chat_message("assistant"):
        st.markdown(response)

    # Save updated chat history
    save_history(st.session_state["messages"])
